### ISSUE TITLE
Immutable Infrastructure

### ISSUE THREAD

**Issue by blockchainunchained** [MaximilianMeister/ethereum-validator#11]
Have we considered using a tool like Packer to produce ISO files with your keys baked in? All you'd need to do is put this ISO onto a USB Thumb Drive and pop it into any spare computer. When it boots it will start validating. It would be advisable to only ever make one USB drive. 

The only bit that isn't immutable is the slashing protection database, I've not worked out how to do that bit yet.

**Comment by MaximilianMeister** [comment]
Not sure if this goes beyond the ansible role characteristics of this repository, but I haven't used packer yet and I can't imagine too much right now about the details of it.

When you say immutable, would it also mean theat you can't update a running system which was built like that?

**Comment by blockchainunchained** [comment]
An immutable server is never modified.

In the case of an update you build a new image, tear down the old one and deploy the new one.

Packer basically grabs an Ubuntu ISO, installs it in a VM, runs Ansible on top of it and turns the result back into an image. 

I agree it may be out of scope for this package, I will probably create a new package with this one as a dependency. 

Thanks for the advice.

**Comment by blockchainunchained** [comment]
Closing - out of scope.
