### ISSUE TITLE
Using a role to do the security and NTP stuff instead of doing it ourselves?

### ISSUE THREAD

**Issue by blockchainunchained** [MaximilianMeister/ethereum-validator#3]
What about suggesting users combine this role with a role like https://github.com/E2AN/CIS-Ubuntu-20.04-Ansible

This would let us remove the security stuff and the NTP stuff whilst likely doing a better job of it. 

The example playbook could show how to call the security stuff first.

**Comment by MaximilianMeister** [comment]
@blockchainunchained sounds good if there's already something to reuse, although i would need to find the time first to see what the role is doing

**Comment by blockchainunchained** [comment]
I'll try and take a look at this today.

**Comment by blockchainunchained** [comment]
The only issue with combining the role above and this role is you need to make sure you set:

```
[ssh_connection]
pipelining=True
```

in your ansible.cfg file.

**Comment by blockchainunchained** [comment]
Closing in favour of https://github.com/MaximilianMeister/ethereum-validator/issues/17 as you can't attack what isn't there.
