### ISSUE TITLE
System keeps restarting when run on bare metal.

### ISSUE THREAD

**Issue by blockchainunchained** [MaximilianMeister/ethereum-validator#7]
It does not get passed the check if restart is needed phase. I'll try and take a look at this as I will be running on bare metal.

**Comment by MaximilianMeister** [comment]
I must say I've never had a reboot yet in my testing because the ubuntu update channel seems to have not released any kernel updates yet (or sth similar that requires a reboot)... so this is currently untested, thanks for checking!

**Comment by MaximilianMeister** [comment]
@blockchainunchained I just did the test, on my system there was a reboot necessary and it worked as expected. Did you have a chance to reproduce it?

**Comment by blockchainunchained** [comment]
I cannot reproduce this any more it must have been something peculiar to my setup. Closing.
