### ISSUE TITLE
Setup Github CI to run Travis

### ISSUE THREAD

**Issue by blockchainunchained** [MaximilianMeister/ethereum-validator#9]
We will need to set Travis to generate keys but there is a skeleton .travis.yml file already.

**Comment by MaximilianMeister** [comment]
Yeah would be nice to run the `molecule test` on travis. But we have to either omit the idempotency checks of molecule or allow them to fail.

**Comment by MaximilianMeister** [comment]
I've created some keys for CI. I found it easier than to figure out how to autogenerate them each time. But this can be changed also later if needed.

**Comment by MaximilianMeister** [comment]
@blockchainunchained thanks for the input, and feel free to rebae your PR's now to give them a testrun on travis
